# Generated by Django 4.0.4 on 2022-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
    ]
